services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    user: 501:20
    volumes:
      - /Users/olivier/projects/jellyfin/config:/config
      - /Users/olivier/projects/jellyfin/cache:/cache
      - type: bind
        source: /Users/olivier/movies
        target: /media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.13:8096